-- Copy and paste this into the Supabase SQL Editor to create your database tables

CREATE TABLE public.posts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    slug text not null unique,
    category text not null,
    publish_date text,
    image_url text,
    excerpt text,
    content text,
    author text default 'Ahmed Rakib',
    read_time text default '5 মিনিট'
);

-- Turn off Row Level Security (RLS) temporarily so we can insert data from the migration script
ALTER TABLE public.posts DISABLE ROW LEVEL SECURITY;
